pub const REGISTERED_COMMANDS: &[&str] = &[
    "sidecar_hello",
    "sidecar_health",
    "sidecar_cancel",
    "sidecar_shutdown",
    "config_get_all",
    "config_save_system",
    "logs_query",
    "chat_send",
    "chat_retry",
    "diagnostics_run",
    "diagnostics_export",
    "tools_list",
    "tools_call",
    "tools_audit_query",
    "plugins_status",
    "plugins_refresh",
    "plugins_enable",
    "plugins_disable",
    "mcp_list_servers",
    "mcp_refresh",
    "mcp_call_tool",
    "security_list_grants",
];

pub const PET_ALLOWED_COMMANDS: &[&str] = &["sidecar_cancel", "chat_send"];

pub const SECURITY_CLASSIFIED_COMMANDS: &[(&str, &str)] = &[
    ("sidecar_hello", "sidecar.lifecycle"),
    ("sidecar_health", "sidecar.lifecycle"),
    ("sidecar_cancel", "sidecar.lifecycle"),
    ("sidecar_shutdown", "sidecar.lifecycle"),
    ("config_get_all", "config.read.redacted"),
    ("config_save_system", "config.write.system"),
    ("logs_query", "logs.read.redacted"),
    ("chat_send", "chat.send"),
    ("chat_retry", "chat.retry"),
    ("diagnostics_run", "diagnostics.run"),
    ("diagnostics_export", "diagnostics.export"),
    ("tools_list", "tools.list"),
    ("tools_call", "tools.call"),
    ("tools_audit_query", "tools.audit_query"),
    ("plugins_status", "plugins.status"),
    ("plugins_refresh", "plugins.refresh"),
    ("plugins_enable", "plugins.enable"),
    ("plugins_disable", "plugins.disable"),
    ("mcp_list_servers", "mcp.list_servers"),
    ("mcp_refresh", "mcp.refresh"),
    ("mcp_call_tool", "mcp.call_tool"),
    ("security_list_grants", "security.list_grants"),
];
