export const SCHEMA_HASH = 'ee71fbdbf2a94a2696a62b696641ed75265c31adc0f34ffcfd69270b9e3a60a9' as const

export const RPC_METHODS = [
  'sidecar.hello',
  'sidecar.health',
  'sidecar.shutdown',
  'sidecar.cancel',
  'sidecar.task_snapshot',
  'config.get_all',
  'config.save_api',
  'config.save_system',
  'config.save_memory',
  'config.save_agent',
  'config.save_mcp',
  'config.validate',
  'character.list',
  'character.get',
  'character.save',
  'character.sync_assets',
  'character.delete',
  'character.protect_core_files',
  'chat.send',
  'chat.retry',
  'chat.proactive_state',
  'proactive.start',
  'proactive.stop',
  'proactive.notify_interaction',
  'proactive.update_context',
  'tts.synthesize',
  'stt.begin_recording',
  'stt.stop_recording',
  'stt.transcribe',
  'ocr.capture',
  'ocr.recognize',
  'ocr.cleanup',
  'logs.query',
  'logs.subscribe',
  'logs.export',
  'logs.open_location',
  'tools.list',
  'tools.call',
  'tools.audit_query',
  'plugins.refresh',
  'plugins.enable',
  'plugins.disable',
  'plugins.import',
  'plugins.status',
  'mcp.list_servers',
  'mcp.save_server',
  'mcp.refresh',
  'mcp.call_tool',
  'mcp.stop_server',
  'security.approve',
  'security.deny',
  'security.revoke_grant',
  'security.list_grants',
  'diagnostics.run',
  'diagnostics.export',
  'diagnostics.open_report',
  'handles.read_range',
  'handles.read_page',
  'handles.release',
  'handles.stat',
] as const

export const RPC_EVENTS = [
  'security.confirm_required',
  'chat.started',
  'chat.delta',
  'chat.done',
  'chat.error',
  'chat.cancelled',
  'log.appended',
  'diagnostics.progress',
  'diagnostics.done',
  'diagnostics.error',
  'diagnostics.cancelled',
  'tool.audit',
  'sidecar.crashed',
  'sidecar.restarted',
  'tts.started',
  'tts.done',
  'tts.error',
  'tts.cancelled',
  'stt.started',
  'stt.done',
  'stt.error',
  'stt.cancelled',
  'ocr.progress',
  'ocr.done',
  'ocr.error',
  'ocr.cancelled',
  'tool.done',
  'tool.error',
  'tool.cancelled',
  'logs.export.done',
  'logs.export.error',
  'logs.export.cancelled',
] as const

export type RpcMethod = (typeof RPC_METHODS)[number]
export type RpcEvent = (typeof RPC_EVENTS)[number]

export interface RpcError {
  code: string
  message: string
  user_message: string
  retryable: boolean
  details: Record<string, unknown>
}
